export const eventData = {
  HEADLINE3: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  HEADLINE4: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE5: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  HEADLINE6: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  HEADLINE7: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  HEADLINE8: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  BOX3: { a: "box", D: "fadeInLeft", A: "1s" },
  HEADLINE9: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  HEADLINE10: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInLeft",
    A: "1s",
  },
  HEADLINE11: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  GROUP1: { a: "group", D: "fadeInRight", A: "1s" },
  HEADLINE12: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  HEADLINE13: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInRight",
    A: "1s",
  },
  HEADLINE14: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  BOX6: { a: "box", D: "fadeInRight", A: "1s" },
  BOX7: { a: "box", D: "flipInX", A: "1s" },
  HEADLINE15: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE16: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE17: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE18: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE19: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE20: { "option.is_product_mapping_name_custom": true, a: "headline" },
  GROUP7: { a: "group", D: "fadeInUp", A: "1s" },
  GROUP8: { a: "group", D: "fadeInUp", A: "1s" },
  HEADLINE21: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  HEADLINE22: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  HEADLINE23: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  HEADLINE24: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  HEADLINE25: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  HEADLINE26: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE27: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE28: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE29: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "pulse",
    A: "1s",
  },
  HEADLINE31: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE32: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE33: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE34: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE35: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE36: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE37: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE38: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE39: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE40: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE41: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE42: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE43: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE44: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE45: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE46: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE47: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE48: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE49: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE50: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE51: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE52: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE53: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE54: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE55: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE56: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE57: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE58: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE59: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE60: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE61: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE62: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE63: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE64: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE65: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE66: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE67: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE68: { "option.is_product_mapping_name_custom": true, a: "headline" },
  IMAGE11: { a: "image", D: "bounceIn", A: "1s" },
  HEADLINE69: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "pulse",
    A: "1s",
  },
  IMAGE13: { a: "image", D: "fadeInUp", A: "1s" },
  HEADLINE70: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE71: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE72: { "option.is_product_mapping_name_custom": true, a: "headline" },
  GROUP11: { a: "group", D: "fadeInRight", A: "1s" },
  HEADLINE73: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE74: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE75: { "option.is_product_mapping_name_custom": true, a: "headline" },
  GROUP12: { a: "group", D: "fadeInRight", A: "1s" },
  HEADLINE76: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE77: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE78: { "option.is_product_mapping_name_custom": true, a: "headline" },
  GROUP13: { a: "group", D: "fadeInRight", A: "1s" },
  HEADLINE79: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE80: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE81: { "option.is_product_mapping_name_custom": true, a: "headline" },
  GROUP14: { a: "group", D: "fadeInRight", A: "1s" },
  IMAGE14: { a: "image", D: "fadeInUp", A: "1s" },
  IMAGE15: { a: "image", D: "fadeInUp", A: "1s" },
  IMAGE16: { a: "image", D: "fadeInUp", A: "1s" },
  HEADLINE82: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE83: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE84: { "option.is_product_mapping_name_custom": true, a: "headline" },
  GROUP16: { a: "group", D: "fadeInUp", A: "1s" },
  HEADLINE85: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE86: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE87: { "option.is_product_mapping_name_custom": true, a: "headline" },
  GROUP18: { a: "group", D: "fadeInLeft", A: "1s" },
  HEADLINE88: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE89: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE90: { "option.is_product_mapping_name_custom": true, a: "headline" },
  GROUP19: { a: "group", D: "fadeInLeft", A: "1s" },
  HEADLINE91: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE92: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE93: { "option.is_product_mapping_name_custom": true, a: "headline" },
  GROUP20: { a: "group", D: "fadeInLeft", A: "1s" },
  HEADLINE94: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE95: { "option.is_product_mapping_name_custom": true, a: "headline" },
  GROUP21: { a: "group", D: "fadeInLeft", A: "1s" },
  IMAGE17: { a: "image", D: "fadeInUp", A: "1s" },
  IMAGE18: { a: "image", D: "fadeInUp", A: "1s" },
  IMAGE19: { a: "image", D: "fadeInUp", A: "1s" },
  GROUP22: { a: "group", D: "fadeInUp", A: "1s" },
  HEADLINE97: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  BOX9: { a: "box", D: "fadeInLeft", A: "0.5s" },
  BOX10: { a: "box", D: "fadeInLeft", A: "0.7s" },
  BOX11: { a: "box", D: "fadeInLeft", A: "1s" },
  BOX12: { a: "box", D: "fadeInLeft", A: "1.3s" },
  BOX13: { a: "box", D: "fadeInLeft", A: "1.5s" },
  BOX15: { a: "box", D: "fadeInUpBig", A: "1s" },
  BOX16: { a: "box", D: "fadeInUpBig", A: "1s" },
  BOX17: { a: "box", D: "fadeInUpBig", A: "1s" },
  BOX18: { a: "box", D: "fadeInUpBig", A: "1s" },
  GALLERY1: { a: "gallery", ah: true, ae: 2 },
  HEADLINE107: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  COUNTDOWN_ITEM1: { a: "countdown_item", bY: "day" },
  COUNTDOWN_ITEM2: { a: "countdown_item", bY: "hour" },
  COUNTDOWN_ITEM3: { a: "countdown_item", bY: "minute" },
  COUNTDOWN_ITEM4: { a: "countdown_item", bY: "seconds" },
  COUNTDOWN1: { a: "countdown", bX: "endtime", bT: 1755277200000 },
  HEADLINE108: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE109: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE110: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE111: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  HEADLINE112: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  GROUP30: {
    a: "group",
    cs: [
      {
        dr: "action",
        dv: "_blank",
        dw: "https://maps.app.goo.gl/sTvRuYtThtCf274k9",
        a: "link",
      },
    ],
    D: "pulse",
    A: "0s",
  },
  GROUP31: { a: "group", D: "fadeInLeft", A: "1s" },
  HEADLINE113: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  BOX23: { a: "box", D: "fadeInLeft", A: "1s" },
  HEADLINE114: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE115: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  HEADLINE117: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE119: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE122: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  HEADLINE123: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
    D: "fadeInUp",
    A: "1s",
  },
  BUTTON_TEXT2: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
  },
  BUTTON2: { a: "button", D: "fadeInUp", A: "1s" },
  FORM_ITEM2: { a: "form_item", bS: "text", bQ: 1 },
  FORM_ITEM3: { a: "form_item", bS: "textarea", bQ: 4 },
  FORM_ITEM4: { a: "form_item", bS: "select", bQ: 3 },
  FORM_ITEM5: { a: "form_item", bS: "select", bQ: 4 },
  FORM_ITEM6: { a: "form_item", bS: "select", bQ: 5 },
  FORM2: {
    "option.dynamic_form_config":
      "&#123;&#34;configs&#34;:[],&#34;default_actions&#34;:[&#123;&#34;text_thankyou_value&#34;:&#34;Cảm ơn bạn đã quan tâm!&#34;,&#34;type&#34;:&#34;form_open_popup&#34;,&#34;no_delete&#34;:true,&#34;id_open_popup&#34;:&#34;POPUP1&#34;&#125;]&#125;",
    a: "form",
    bP: "6635f69f2dbe070012bd1e29",
    bM: true,
    by: true,
    bx: true,
    D: "fadeInUp",
    A: "1s",
  },
  BUTTON_TEXT3: {
    "option.is_product_mapping_name_custom": true,
    a: "headline",
  },
  BUTTON3: {
    a: "button",
    cs: [{ dr: "action", dw: "POPUP2", a: "popup" }],
    F: "fadeInUp",
    C: "1s",
  },
  POPUP1: {
    a: "popup",
    X: "default",
    U: "background-color: rgba(0, 0, 0, 0.5);",
  },
  PARAGRAPH1: { "option.is_product_mapping_name_custom": true, a: "paragraph" },
  PARAGRAPH2: { "option.is_product_mapping_name_custom": true, a: "paragraph" },
  POPUP2: {
    a: "popup",
    X: "default",
    U: "background-color: rgba(0, 0, 0, 0.5);",
  },
  HEADLINE130: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE131: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE132: { "option.is_product_mapping_name_custom": true, a: "headline" },
  GROUP36: { a: "group", D: "fadeInUp", A: "1s" },
  HEADLINE133: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE134: { "option.is_product_mapping_name_custom": true, a: "headline" },
  HEADLINE135: { "option.is_product_mapping_name_custom": true, a: "headline" },
  GROUP37: { a: "group", D: "fadeInUp", A: "1s" },
  GROUP38: { a: "group", D: "fadeInUp", A: "1s" },
  GROUP39: { a: "group", D: "fadeInUp", A: "1s" },
  HEADLINE136: { "option.is_product_mapping_name_custom": true, a: "headline" },
  IMAGE41: { a: "image", cs: [{ dr: "action" }] },
  GROUP40: {
    a: "group",
    aB: true,
    ax: "bottom_right",
    au: "0px",
    ar: "0px",
    ao: "15px",
    al: "10px",
  },
};
