import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/css2.css";
import "./styles/ladi.css";
import "./styles/page.css";
import "./styles/element.css";
// import "./js/ladipage.formdata.min.js.download";
// import "./js/ladipagev3.min.js.download";
import Script from "next/script";
import { eventData } from "./eventData";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta httpEquiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Đám cưới Tuấn Nguyễn &amp; Huyền Lê</title>
        <meta httpEquiv="Cache-Control" content="no-cache" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta httpEquiv="Expires" content="-1" />
        <meta name="keywords" content="" />
        <meta name="description" content="Đám cưới Tuấn Nguyễn & Huyền Lê" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          id="viewport"
          name="viewport"
          content="width=420,user-scalable=no,initial-scale=3.657142857142857,minimum-scale=3.657142857142857,maximum-scale=3.657142857142857"
        />
        <link rel="canonical" href="https://camcui.vn/tuanhuyennn" />
        <meta property="og:url" content="https://camcui.vn/tuanhuyennn" />
        <meta property="og:title" content="Đám cưới Tuấn Nguyễn & Huyền Lê" />
        <meta property="og:type" content="website" />
        <meta
          property="og:image"
          content="https://static.ladipage.net/6322a62f2dad980013bb5005/508445378_1281875497280711_1109684595019462715_n-20250719105331-yjczc.jpg"
        />
        <meta
          property="og:description"
          content="Đám cưới Tuấn Nguyễn & Huyền Lê"
        />
        <meta name="format-detection" content="telephone=no" />
        <link
          rel="icon"
          type="image/x-icon"
          href="https://static.ladipage.net/6322a62f2dad980013bb5005/untitled-1-20250409032644-v_4bn.png"
        />
        <link
          rel="shortcut icon"
          href="https://static.ladipage.net/6322a62f2dad980013bb5005/untitled-1-20250409032644-v_4bn.png"
        />
        <link
          rel="apple-touch-icon"
          href="https://static.ladipage.net/6322a62f2dad980013bb5005/untitled-1-20250409032644-v_4bn.png"
        />
        <link
          rel="apple-touch-icon-precomposed"
          href="https://static.ladipage.net/6322a62f2dad980013bb5005/untitled-1-20250409032644-v_4bn.png"
        />
        <meta
          name="msapplication-TileImage"
          content="https://static.ladipage.net/6322a62f2dad980013bb5005/untitled-1-20250409032644-v_4bn.png"
        />
        <meta name="revisit-after" content="days" />
        <link rel="dns-prefetch" />
        <link
          rel="preconnect"
          href="https://fonts.googleapis.com/"
          crossOrigin=""
        />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com/"
          crossOrigin=""
        />
        <link rel="preconnect" href="https://w.ladicdn.com/" crossOrigin="" />
        <link rel="preconnect" href="https://s.ladicdn.com/" crossOrigin="" />
        <link
          rel="preconnect"
          href="https://api1.ldpform.com/"
          crossOrigin=""
        />
        <link rel="preconnect" href="https://a.ladipage.com/" crossOrigin="" />
        <link
          rel="preconnect"
          href="https://api.sales.ldpform.net/"
          crossOrigin=""
        />
        
        <Script
        src="/js/ladipagev3.min.js"
        strategy="beforeInteractive"
      />
      <Script
        src="/js/ladipage.formdata.min.js"
        strategy="beforeInteractive"
      />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        <script
          id="script_event_data"
          type="application/json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(eventData),
          }}
        />
      </body>
    </html>
  );
}
